### ISSUE TITLE
Numerical instability of gamma*sin

### ISSUE THREAD

**Issue by mavenlin** [QijingZheng/pySBT#1]
We spotted this line
https://github.com/QijingZheng/pySBT/blob/main/pysbt/pysbt.py#L132
is implemented via a direct multiplication of gamma and sin function, which has large error when the t value is large.

The original paper proposes a more stable procedure, would you consider implement it in your package?

**Comment by QijingZheng** [comment]
Hi

Thank you very much for your prompt! I've replace the line using the more stable form of Eq. (19) 

Best
Qijing

**Comment by mavenlin** [comment]
Hi Qijing, thanks a lot, we confirm it is more stable and can work with larger t now.
